### ISSUE TITLE
Environment Support

### ISSUE THREAD

**Issue by h4kbas** [emrekeskinmac/emr#1]
In order to run projects in some specific scenarios like development / production mode or to change any config related to it, we can also have environment variable support like .env file but embedded inside the yaml file.

For example:

```
projects:
  order:
    title: Order
    run: cd folder && npm run serve
    env:
       - "NODE_ENV=production"
```
